// <auto-generated />
namespace ORP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Alteredcity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteredcity));
        
        string IMigrationMetadata.Id
        {
            get { return "202002271505037_Altered city"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
